### ISSUE TITLE
Ironically, errors out on Fatal Error log lines

### ISSUE THREAD

**Issue by dcinzona** [gavignon/sfdc-log#1]
In the case of a Fatal Error where SOQL Limits are exceeded (just an example I have), logParts has a length of 3 (only 2 pipes `|`)

Log Line:
`15:09:54.680 (22708163254)|FATAL_ERROR|System.LimitException: Too many SOQL queries: 101`

Erroring line:
```javascript
      newPoint.opDetails = (logParts[4] ? logParts[4] : logParts[3])
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");
```

Screenshot of error in dev console:

![Screen Shot 2022-04-14 at 12 38 18 PM](https://user-images.githubusercontent.com/52411/163434417-20014d6c-5e9e-42f8-894f-bb67a0387a27.png)

**Comment by gavignon** [comment]
Thanks @dcinzona for raising this issue!
It must be fixed now and it's deployed to Heroku.
